"""update models

Revision ID: 59a08c81f26f
Revises: a8cf1be8d327
Create Date: 2025-11-17 12:56:35.197702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a08c81f26f'
down_revision: Union[str, None] = 'a8cf1be8d327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_type')
    # ### end Alembic commands ###
