"""обновил модели

Revision ID: cdd9554e3cff
Revises: 991d4197c79f
Create Date: 2025-10-02 18:37:54.947096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd9554e3cff'
down_revision: Union[str, None] = '991d4197c79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('extracted_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'extracted_text')
    # ### end Alembic commands ###
